AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  proj-waterfall-backend

  AWS SAM Template for the wireframe/representative APIs that are used to help
  support experimentation with https://mpyne-navy.github.io/proj-waterfall/
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetPersonnelRecordFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-record/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        GetPersonnelRecord:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /record/pers/{user_id}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetPersonnelRecordApi:
    Description: "API Gateway endpoint URL for Prod stage for GetPersonnelRecord function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/record/pers"
  GetPersonnelRecordFunction:
    Description: "Retrieve basic personnel record information - Lambda Function ARN"
    Value: !GetAtt GetPersonnelRecordFunction.Arn
  GetPersonnelRecordFunctionIamRole:
    Description: "Implicit IAM Role created for GetPersonnelRecord function"
    Value: !GetAtt GetPersonnelRecordFunctionRole.Arn
